# Production Profile Overrides
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway MUST be enabled in prod
spring.flyway.enabled=true

# Logging
logging.level.com.backend.revol_store=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

# Restricted CORS
#app.cors.allowed-origins=https://revol-store.com,https://www.revol-store.com
app.cors.allowed-origins=https://revolstore.netlify.app,http://localhost:3000
# No stacktraces
server.error.include-stacktrace=never
